# Generated by Django 5.1.4 on 2024-12-18 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aghendi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='edited_agendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
