# Generated by Django 5.1.4 on 2024-12-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aghendi', '0002_agenda_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaelement',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendaelement',
            name='emission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
