# Generated by Django 5.1.4 on 2024-12-18 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aghendi', '0004_agendaelement_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgendaElementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('agenda_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='aghendi.agendaelement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_element_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'agenda_element')},
            },
        ),
    ]
