# Generated by Django 5.1.4 on 2024-12-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aghendi', '0005_useragendaelementstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAgendaElementStatus',
        ),
    ]
