# Generated by Django 5.1.4 on 2024-12-19 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aghendi', '0007_agendaelement_completed_agendaelement_nothing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_agendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
